### PR TITLE
FIx state transition error on login

### LINKED ISSUE #146: Redirect to newsfeed after log-in
Child of #145

### LINKED ISSUE #184: Fix state transition error on login
Getting `Warning: Cannot update during an existing state transition` on login mutation

### PR DESCRIPTION
**Pull request by thinktwice13**
Seemed to have been kinda forgotten, but we were getting `Warning: Cannot update during an existing state transition` during login mutation. 
- Moved the auth mutation to `componentDidMount` closes #184
- Also changed default post-login route to `/feed` - closes #146

### CODE REVIEW

File: src/components/Login/index.jsx [hunk 1]
```diff
@@ -1,45 +1,72 @@
...
+    if (error) this.setState({ error: error.message })
+
+    const {
+      userAuthGithub: { user, access_token }
+    } = data
+    // Save new access_token
+    localStorage.token = access_token
+
+    // Redirect to pre-login navigated route
+    redirect
```
Comment (the-vampiire) [inline src/components/Login/index.jsx]: replace ternary with `history.push(redirect || "/feed");`
remove `loginRedirectSwitch`
