### PR TITLE
Style/style fixes

### LINKED ISSUE #85: Resize images in landing
Child of #145

- animal icons
- past projects
- profie shots of testimonials

### PR DESCRIPTION
**Pull request by serpient**
#85 Resize images in landing
#200 refactor header dropdown
#201 Fix newsfeed responsive design
#203 add 20px padding on all pages
#214 when viewing public profile thats empty, show a card that says "nothing here yet! check back later!"
#218 Center dynamic form submit btn
- Team Standup Form Styling
- Added a disabled submit button so users know that they need to fix their form before they can submit

## Live Renders
image

image

image

### CODE REVIEW

File: src/components/FeedPortal/components/TeamCard.jsx [hunk 1]
```diff
@@ -10,9 +10,9 @@ const TeamCard = ({ team }) => {
         <InfoComponents team={team} />
       </div>
       <div className="team-card-buttons-container">
-        <Link to={"/project/" + team.project.id + "/workspace"} className="user-btn">Team Workspace</Link>
+        {/* <Link to={"/project/" + team.project.id + "/workspace"} className="user-btn">Team Workspace</Link> */}
         <Link to={"/project/" + team.project.id} className="user-btn">Project Showcase</Link>
-        <Link className="user-btn" to={"/team/checkin/" + team.cohort.id}>Team Standups</Link>
+        <Link className="user-btn" to={"/team/" + team.cohort.id + "/standup"}>Team Standups</Link>
```
Comment (the-vampiire) [inline src/components/FeedPortal/components/TeamCard.jsx]: this one should be the `team.id`
also lets use template strings for injecting variables
\`/team/${team.id}/standup\`

File: src/components/DynamicForm/components/DynamicFormContainer.jsx [hunk 2]
```diff
@@ -171,13 +171,26 @@ class DynamicFormContainer extends React.Component {
       </React.Fragment>
     );
   };
-  
+
```
Comment (the-vampiire) [inline src/components/DynamicForm/components/DynamicFormContainer.jsx]: the renderSubmitButton can be refactored to handle both cases

File: src/components/DynamicForm/components/DynamicFormContainer.jsx [hunk 3]
```diff
@@ -171,13 +171,26 @@ class DynamicFormContainer extends React.Component {
...
+  renderDisabledSubmitBtn = () => {
+    return (
+      <React.Fragment>
+        <hr className="form-hline" />
+        <input
+          className="form-btn--disabled"
+          disbaled
+          value="Can't Submit Yet"
```
Comment (the-vampiire) [inline src/components/DynamicForm/components/DynamicFormContainer.jsx]: what do you think of changing this to "Incomplete"? It's visually closer in size to Submit

File: src/components/TeamStandup/index.jsx [hunk 4]
```diff
@@ -57,12 +58,12 @@ class TeamStandup extends React.Component {
 
     if (error) return <Error error={error.message} />;
     if (response) return <Redirect to="/feed" />;
-// TODO: needs styling
+    // TODO: needs styling
```
Comment (the-vampiire) [inline src/components/TeamStandup/index.jsx]: can remove

File: src/components/UserProfile/index.jsx [hunk 5]
```diff
@@ -43,7 +43,8 @@ class UserProfile extends React.Component {
   }
 
   render() {
-    let { user, currentTeams, pastTeams, pendingApproval } = this.state;
+    let { user, currentTeams, pastTeams, pendingApproval, editable } = this.state;
+    console.log(editable);
```
Comment (the-vampiire) [inline src/components/UserProfile/index.jsx]: can remove

File: src/components/UserProfile/index.jsx [hunk 6]
```diff
@@ -65,50 +66,52 @@ class UserProfile extends React.Component {
...
-                      </React.Fragment>
-
-                    )
-                  })
-                  : null
+                && pendingApproval.map((cohort, index) => {
+                  return (
+                    <React.Fragment key={cohort.id + "_" + index}>
+                      <div className="user-voyage-title">Upcoming Voyages</div>
+                      <Cards.PendingApprovalVoyageCard
```
Comment (the-vampiire) [inline src/components/UserProfile/index.jsx]: how complex would it be to render "Pending Approval" but then add a "APPLY" button if `editable` is true? meaning if you view someone elses profile and they are pending approval you can apply to the same voyage

File: src/components/UserProfile/index.jsx [hunk 7]
```diff
@@ -65,50 +66,52 @@ class UserProfile extends React.Component {
...
-
-                  </div>
-                </section>
-                : null
+              && <section className="user-voyage">
+                <div className="user-voyage-title">Past Voyages</div>
+                <div>
+                  {pastTeams.map((team, index) => {
+                    return (
+                      <Cards.PreviousVoyageCardWithTeam
```
Comment (the-vampiire) [inline src/components/UserProfile/index.jsx]: same as above

File: src/components/DynamicForm/components/DynamicFormContainer.jsx (hunk 3 above)
Comment (serpient) [reply src/components/DynamicForm/components/DynamicFormContainer.jsx]: i can go both ways. But I chose "cant submit yet" because it sounded friendlier, and still lets the user know their form is missing something. but if thats not a good enough reason,  ill change it !
